name: Backend Lambda Deploy

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }} 

      - name: Zip Lambda 1
        run: |
          cd backend/generate-presigned-url
          zip -r lambda.zip .

      - name: Zip Lambda 2
        run: |
          cd backend/process-uploaded-file
          zip -r lambda.zip .

      - name: Deploy Lambda 1
        run: |
          aws lambda update-function-code \
            --function-name devops-accelerator-generate-presigned-url \
            --zip-file fileb://backend/generate-presigned-url/lambda.zip

      - name: Deploy Lambda 2
        run: |
          aws lambda update-function-code \
            --function-name devops-accelerator-process-uploaded-file \
            --zip-file fileb://backend/process-uploaded-file/lambda.zip